apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ox1uq1oxy-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ox1uq1oxy-java-springboot-gitops